version: "3.8"
services:
    api:
        # image: -
            build:
                dockerfile: Dockerfile
                context: .
            depends_on: 
                - mongoDB
            environment: 
                DATABASE_URL: mongodb+srv://<USER>:<PASSWORD>@taskappcluster.96ojv.mongodb.net/ORBIT_DB?retryWrites=true&w=majority
                NODE_ENV: development
                PORT: 5000
            ports:
                - 8080:5000
            
        